name: post_ui
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3 # Update to the latest version of http
  shared_preferences: ^2.0.8
  flutter_lints: ^1.0.0 # Update to the latest version of flutter_lints
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
